#!/bin/bash
#####################################################################################################
#  Author :   sarath kumar
#  Date created : 15 -04-2021
#  description : copy the file to /tmp/found.txt from sample.txt
 
#  Date modified: 15 -04-2021

#######################################################################################################

ls /home/welcome/Desktop/data/sample.txt &> /dev/null

if [ $? -eq 0 ]
  then 
     cp /home/welcome/Desktop/data/sample.txt /tmp/found.txt
else
	    echo "sample.txt is not exist"
fi 

