#!/bin/bash

#######################
#authorSarath kumar
#date created: 16/04/21
#description: This service for running 
#date modified: 16/04/21
#######################

if [ `whoami` == "root" ]
then

echo "[Service]
	WorkingDirectory=~/Desktop
	ExecStart=~/Desktop/servicescript.bash
	Restart=on-failure
	
	[Install]
	WantedBy=default.target" > /etc/systemd/system/ex13.service

sudo systemctl daemon-reload
sudo systemctl enable exercise 13-script
sudo systemctl start exercise 13-script
sudo systemctl status exercise 13-script


else
       echo "you are not root" 
	
fi	
