#! /bin/bash

######################################################
#Author: Sarath kumar
#Date Created: 15/04/2021
#Date Modified: 15/04/2021
# Description : create directory and file
#################################################

mkdir /home/welcome/Desktop/data

touch  /home/welcome/Desktop/data/sample.txt

echo "This is sample file "  >  /home/welcome/Desktop/data/sample.txt
